@startuml Restaurant

' notes
' note top of Restaurant : This is the main class of the module
' note left of Table : This Represents a sing table in the Restaurant 

class Restaurant {
    name STRING
    image_url STRING
    menus Array<Menu>
    tables Array<Table>

    constructor(name: STRING, image_url: STRING, tables: Array<Table>?, menus Array<Menu>?)
    getMenus()
    getMenu(name: STRING)
    getItem(name: STRING)
    getTables()
    getBookings()
    getBooking(date: DATE)
}

class Menu {
    name STRING
    items Array<Item>

    getItem(name: STRING)
    addItem(item: Item)
    removeItem(name: STRING)
}

class Item {
    name STRING
    ingredients Array<Ingredient>
    price FLOAT

    getAllergens()
}

class Ingredient {
    name STRING
    isAllergen BOOL

    static getInstanceById(id: INT)
    constructor(data: Object)
}

class Table {
    number INT
    seats INT
    bookings Array<Booking>

    getBookings()
    addBooking(booking: Booking)
    removeBooking(booking: Booking)
    cleanBookings()
}

class Booking {
    groupName STRING
    contactNumber STRING
    time DATE

    isExpired()
}



Restaurant--{Menu
Menu--{Item
Item--{Ingredient
Restaurant--{Table
Table--{Booking

@enduml