@startuml Restaurant

' notes
' note top of Restaurant : This is the main class of the module
' note left of Table : This Represents a sing table in the Restaurant 

class Restaurant {
    id INT
    name STRING
    image_url STRING

    static getInstanceById(id: INT)
    constructor(data: Object)
}

class Menu {
    id INT
    name STRING
    restaurantID INT

    static getInstanceById(id: INT)
    constructor(data: Object)
}

class Item {
    id INT
    name STRING
    price FLOAT
    menuID INT

    static getInstanceById(id: INT)
    constructor(data: Object)
}

class Ingredient {
    id INT
    name STRING
    isAllergen BOOL
    itemID INT

    static getInstanceById(id: INT)
    constructor(data: Object)
}

class Table {
    id INT
    number INT
    seats INT
    restaurantID INT

    static getInstanceById(id: INT)
    constructor(data: Object)
}

class Booking {
    id INT
    groupName STRING
    contactNumber STRING
    time DATE
    tableID

    static getInstanceById(id: INT)
    constructor(data: Object)
}



Restaurant--{Menu
Menu--{Item
Item--{Ingredient
Restaurant--{Table
Table--{Booking

@enduml